# -*- coding: utf-8 -*-
"""PBL_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192IRCwDRFsxM_4mwfe1eAJwBZNUQSw4W
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import pandas as pd
import os
import time
from IPython.display import display, clear_output
import urllib.request
try:
    from google.colab import files  # For Google Colab compatibility
except ImportError:
    pass
import io
from PIL import Image
from datetime import datetime

class WasteSortingSystem:
    def __init__(self):
        # Updated color ranges with broader plastic detection
        # HSV color space (Hue, Saturation, Value)
        self.waste_categories = {
            'plastic': {'color_range': [(0, 50, 50), (30, 255, 255)], 'label': 'Plastic'},  # Expanded range for plastic
            'paper': {'color_range': [(20, 20, 70), (35, 100, 255)], 'label': 'Paper'},
            'metal': {'color_range': [(90, 50, 50), (120, 255, 255)], 'label': 'Metal'},
            'glass': {'color_range': [(70, 50, 50), (90, 255, 255)], 'label': 'Glass'},
            'organic': {'color_range': [(35, 50, 50), (70, 255, 255)], 'label': 'Organic'}
        }

        # Add additional common plastic colors (like clear/white and blue plastics)
        self.additional_plastic_ranges = [
            [(160, 0, 200), (180, 30, 255)],  # Clear/white plastics (low saturation)
            [(100, 50, 50), (130, 255, 255)]  # Blue plastics
        ]

        # Load waste detection model (pretrained on waste images)
        # In a real implementation, you'd load a proper ML model here
        self.model_loaded = True
        print("Waste sorting system initialized.")

        # Initialize statistics tracking
        self.stats = {category: 0 for category in self.waste_categories.keys()}
        self.total_processed = 0

        # For simulation purposes - initialize virtual robotic arm
        self.robot_arm = VirtualRobotArm()

        # Create log file for waste sorting operations
        self.log_file = "waste_sorting_log.txt"
        with open(self.log_file, "w") as f:
            f.write(f"Waste Sorting System Log - Started on {datetime.now()}\n")
            f.write("------------------------------------------------------\n")

    def load_sample_images(self):
        """Load sample waste images for demonstration purposes"""
        sample_images = {}

        # Create more realistic synthetic images for each waste type
        # Plastic - common colors like clear, white, blue, and red
        plastic_img = np.ones((300, 300, 3), dtype=np.uint8) * 255  # White base
        # Add some blue plastic bottles
        cv2.rectangle(plastic_img, (50, 50), (150, 250), (255, 0, 0), -1)  # Blue rectangle
        # Add some red plastic packaging
        cv2.rectangle(plastic_img, (200, 100), (280, 200), (0, 0, 255), -1)  # Red rectangle
        sample_images['plastic'] = plastic_img

        # Paper - brownish/yellowish color
        paper_color = [222, 220, 190]  # BGR
        paper_img = np.ones((300, 300, 3), dtype=np.uint8) * paper_color
        sample_images['paper'] = paper_img

        # Metal - silver/gray color
        metal_color = [180, 180, 180]  # BGR
        metal_img = np.ones((300, 300, 3), dtype=np.uint8) * metal_color
        sample_images['metal'] = metal_img

        # Glass - transparent blueish
        glass_color = [200, 230, 230]  # BGR
        glass_img = np.ones((300, 300, 3), dtype=np.uint8) * glass_color
        sample_images['glass'] = glass_img

        # Organic - brownish green
        organic_color = [42, 128, 42]  # BGR
        organic_img = np.ones((300, 300, 3), dtype=np.uint8) * organic_color
        sample_images['organic'] = organic_img

        return sample_images

    def detect_waste(self, image):
        """
        Detect waste in the image using computer vision.
        Returns the waste type and bounding box coordinates.
        """
        # Convert to HSV for easier color segmentation
        hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

        detected_objects = []

        # Detect objects of each waste category based on color
        for category, info in self.waste_categories.items():
            lower, upper = info['color_range']
            mask = cv2.inRange(hsv, np.array(lower), np.array(upper))

            # For plastic, add additional color ranges
            if category == 'plastic':
                for add_range in self.additional_plastic_ranges:
                    add_lower, add_upper = add_range
                    add_mask = cv2.inRange(hsv, np.array(add_lower), np.array(add_upper))
                    mask = cv2.bitwise_or(mask, add_mask)

            # Apply morphological operations to reduce noise
            kernel = np.ones((5, 5), np.uint8)
            mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
            mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

            # Find contours in the mask
            contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

            # Process each contour as a potential waste object
            for contour in contours:
                if cv2.contourArea(contour) > 500:  # Filter small contours
                    x, y, w, h = cv2.boundingRect(contour)
                    confidence = self._calculate_confidence(hsv[y:y+h, x:x+w], lower, upper)

                    # For plastic, check additional confidence with other ranges
                    if category == 'plastic':
                        for add_range in self.additional_plastic_ranges:
                            add_lower, add_upper = add_range
                            add_confidence = self._calculate_confidence(hsv[y:y+h, x:x+w], add_lower, add_upper)
                            confidence = max(confidence, add_confidence)

                    detected_objects.append({
                        'category': category,
                        'label': info['label'],
                        'bbox': (x, y, w, h),
                        'confidence': confidence
                    })

        # Sort by confidence (highest first)
        detected_objects.sort(key=lambda x: x['confidence'], reverse=True)

        return detected_objects

    def _calculate_confidence(self, roi_hsv, lower, upper):
        """Calculate confidence score based on how well the ROI matches the color range"""
        # Simple heuristic: percentage of pixels within the color range
        mask = cv2.inRange(roi_hsv, np.array(lower), np.array(upper))
        return np.count_nonzero(mask) / (roi_hsv.shape[0] * roi_hsv.shape[1] + 1e-10)  # Avoid div by zero

    def classify_waste_by_features(self, image, bbox):
        """
        Use advanced features to classify waste.
        In a real implementation, this would use a proper ML model.
        """
        x, y, w, h = bbox
        roi = image[y:y+h, x:x+w]

        # Extract features
        hsv_roi = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)
        avg_color = np.mean(hsv_roi, axis=(0, 1))

        # Check texture features (simple variance)
        gray_roi = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
        texture_variance = np.var(gray_roi)

        best_match = None
        best_score = -1

        # Create feature vector [hue, saturation, value, texture_variance]
        features = np.append(avg_color, texture_variance)

        for category, info in self.waste_categories.items():
            lower, upper = info['color_range']

            # Calculate base score from color distance
            h_dist = min(abs(avg_color[0] - ((lower[0] + upper[0]) / 2)),
                         180 - abs(avg_color[0] - ((lower[0] + upper[0]) / 2))) / 180.0
            s_dist = abs(avg_color[1] - ((lower[1] + upper[1]) / 2)) / 255.0
            v_dist = abs(avg_color[2] - ((lower[2] + upper[2]) / 2)) / 255.0

            # Combine distances with weights
            color_score = 1.0 - (0.6 * h_dist + 0.2 * s_dist + 0.2 * v_dist)

            # Apply texture-based rules
            # Plastics often have smoother texture (lower variance)
            if category == 'plastic' and texture_variance < 1000:
                color_score += 0.2

            # Paper often has medium texture
            if category == 'paper' and 1000 <= texture_variance <= 3000:
                color_score += 0.2

            # Additional check for plastic's additional ranges
            if category == 'plastic':
                for add_range in self.additional_plastic_ranges:
                    add_lower, add_upper = add_range
                    add_h_dist = min(abs(avg_color[0] - ((add_lower[0] + add_upper[0]) / 2)),
                                     180 - abs(avg_color[0] - ((add_lower[0] + add_upper[0]) / 2))) / 180.0
                    add_score = 1.0 - add_h_dist
                    color_score = max(color_score, add_score)

            if color_score > best_score:
                best_score = color_score
                best_match = category

        return best_match, best_score

    def visualize_detection(self, image, detections):
        """Visualize the detected waste objects with bounding boxes and labels"""
        output = image.copy()

        # Draw bounding boxes and labels
        for detection in detections:
            category = detection['category']
            label = detection['label']
            x, y, w, h = detection['bbox']
            confidence = detection['confidence']

            # Get color for this category
            if category == 'plastic':
                color = (0, 0, 255)  # Red for plastic
            elif category == 'paper':
                color = (255, 255, 0)  # Cyan for paper
            elif category == 'metal':
                color = (0, 255, 0)  # Green for metal
            elif category == 'glass':
                color = (255, 0, 0)  # Blue for glass
            else:  # organic
                color = (0, 255, 255)  # Yellow for organic

            # Draw bounding box
            cv2.rectangle(output, (x, y), (x+w, y+h), color, 2)

            # Draw label with confidence
            label_text = f"{label}: {confidence:.2f}"
            cv2.putText(output, label_text, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX,
                        0.5, color, 2)

        return output

    def sort_waste(self, image):
        """Main function to detect and sort waste in an image"""
        start_time = time.time()

        # Step 1: Detect waste objects in the image
        detections = self.detect_waste(image)

        # If no waste detected
        if not detections:
            print("No waste detected in the image.")
            return image, []

        # Step 2: Process each detected object
        for detection in detections:
            category = detection['category']
            bbox = detection['bbox']

            # Refine classification with more advanced features
            refined_category, confidence = self.classify_waste_by_features(image, bbox)
            detection['category'] = refined_category
            detection['label'] = self.waste_categories[refined_category]['label']
            detection['confidence'] = confidence

            # Update statistics
            self.stats[refined_category] += 1
            self.total_processed += 1

            # Log the detection
            self._log_detection(refined_category, confidence)

            # Simulate robotic arm movement to sort the waste
            x, y, w, h = bbox
            target_x, target_y = x + w//2, y + h//2  # Target center of object
            self.robot_arm.move_to(target_x, target_y)
            self.robot_arm.pickup()
            self.robot_arm.move_to_bin(refined_category)
            self.robot_arm.release()

        # Step 3: Visualize results
        output_image = self.visualize_detection(image, detections)

        # Calculate processing time
        processing_time = time.time() - start_time
        print(f"Processing completed in {processing_time:.2f} seconds")

        return output_image, detections

    def show_statistics(self):
        """Display waste sorting statistics"""
        print("\n===== Waste Sorting Statistics =====")
        print(f"Total waste processed: {self.total_processed}")

        if self.total_processed > 0:
            for category, count in self.stats.items():
                percentage = (count / self.total_processed) * 100
                print(f"{self.waste_categories[category]['label']}: {count} items ({percentage:.1f}%)")

        # Create a simple bar chart
        categories = [self.waste_categories[cat]['label'] for cat in self.stats.keys()]
        counts = list(self.stats.values())

        plt.figure(figsize=(10, 5))
        bars = plt.bar(categories, counts)

        # Color the bars according to waste category colors
        category_colors = {
            'plastic': 'red',
            'paper': 'tan',
            'metal': 'gray',
            'glass': 'skyblue',
            'organic': 'green'
        }

        for i, category in enumerate(self.stats.keys()):
            bars[i].set_color(category_colors[category])

        plt.title('Waste Sorting Results')
        plt.xlabel('Waste Category')
        plt.ylabel('Number of Items')
        plt.tight_layout()
        plt.show()

    def _log_detection(self, category, confidence):
        """Log waste detection to file"""
        with open(self.log_file, "a") as f:
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            f.write(f"{timestamp} - Detected {self.waste_categories[category]['label']} "
                   f"with confidence {confidence:.2f}\n")


class VirtualRobotArm:
    """Simulate a robotic arm for waste sorting"""
    def __init__(self):
        self.x = 0
        self.y = 0
        self.holding = False
        self.bin_positions = {
            'plastic': (100, 500),
            'paper': (300, 500),
            'metal': (500, 500),
            'glass': (700, 500),
            'organic': (900, 500)
        }
        print("Virtual robot arm initialized.")

    def move_to(self, x, y):
        """Move the arm to the specified coordinates"""
        print(f"Moving arm to position ({x}, {y})")
        # Simulate movement time
        time.sleep(0.1)  # Reduced for faster simulation
        self.x, self.y = x, y

    def pickup(self):
        """Simulate picking up an item"""
        if not self.holding:
            print(f"Picking up item at position ({self.x}, {self.y})")
            self.holding = True
            # Simulate pickup time
            time.sleep(0.1)  # Reduced for faster simulation
        else:
            print("Cannot pick up: already holding an item")

    def move_to_bin(self, waste_type):
        """Move to the bin for the specified waste type"""
        if waste_type in self.bin_positions:
            bin_x, bin_y = self.bin_positions[waste_type]
            print(f"Moving to {waste_type} bin at position ({bin_x}, {bin_y})")
            # Simulate movement time
            time.sleep(0.1)  # Reduced for faster simulation
            self.x, self.y = bin_x, bin_y
        else:
            print(f"Unknown bin type: {waste_type}")

    def release(self):
        """Release the held item"""
        if self.holding:
            print(f"Releasing item at position ({self.x}, {self.y})")
            self.holding = False
            # Simulate release time
            time.sleep(0.1)  # Reduced for faster simulation
        else:
            print("Nothing to release: not holding an item")


def create_test_images():
    """Create test images with various waste objects for testing"""
    # Canvas size
    width, height = 800, 600

    # Create a blank image
    mixed_waste = np.ones((height, width, 3), dtype=np.uint8) * 255  # White background

    # Add plastic bottle (blue)
    cv2.rectangle(mixed_waste, (100, 100), (200, 400), (255, 0, 0), -1)  # Blue plastic

    # Add plastic container (red)
    cv2.rectangle(mixed_waste, (300, 150), (450, 250), (0, 0, 255), -1)  # Red plastic

    # Add paper (tan)
    cv2.rectangle(mixed_waste, (500, 100), (700, 200), (200, 220, 230), -1)  # Tan paper

    # Add metal can (gray)
    cv2.circle(mixed_waste, (200, 500), 80, (180, 180, 180), -1)  # Gray metal

    # Add glass bottle (light blue)
    cv2.rectangle(mixed_waste, (400, 400), (500, 550), (230, 216, 173), -1)  # Light blue glass

    # Add organic waste (green)
    cv2.circle(mixed_waste, (650, 450), 100, (0, 150, 0), -1)  # Green organic

    # Create directory for test images if it doesn't exist
    if not os.path.exists("test_images"):
        os.makedirs("test_images")

    # Save the mixed waste image
    cv2.imwrite("test_images/mixed_waste.jpg", mixed_waste)

    # Also create individual waste type images
    waste_types = {
        'plastic_bottle': (255, 0, 0),  # Blue
        'plastic_container': (0, 0, 255),  # Red
        'paper': (200, 220, 230),  # Tan
        'metal': (180, 180, 180),  # Gray
        'glass': (230, 216, 173),  # Light blue
        'organic': (0, 150, 0)  # Green
    }

    for waste_name, color in waste_types.items():
        waste_img = np.ones((400, 400, 3), dtype=np.uint8) * 255  # White background

        if 'plastic' in waste_name or 'paper' in waste_name or 'glass' in waste_name:
            # Rectangle for bottles, containers, paper
            cv2.rectangle(waste_img, (100, 50), (300, 350), color, -1)
        else:
            # Circle for metal cans, organic waste
            cv2.circle(waste_img, (200, 200), 150, color, -1)

        cv2.imwrite(f"test_images/{waste_name}.jpg", waste_img)

    print(f"Test images created and saved in 'test_images' directory")
    return mixed_waste


def run_demo():
    """Run a demonstration of the waste sorting system"""
    print("Initializing Automated Waste Sorting System...")
    system = WasteSortingSystem()

    # Options for getting images
    print("\nPlease select an option to get waste images:")
    print("1. Use sample synthetic images")
    print("2. Upload your own images")
    print("3. Use webcam (if available)")
    print("4. Create and use test images")

    choice = input("Enter your choice (1-4): ")

    if choice == '1':
        # Use sample synthetic images
        sample_images = system.load_sample_images()

        for category, image in sample_images.items():
            print(f"\nProcessing {category} sample...")
            output_image, detections = system.sort_waste(image)

            plt.figure(figsize=(12, 6))
            plt.subplot(1, 2, 1)
            plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
            plt.title('Original Image')
            plt.axis('off')

            plt.subplot(1, 2, 2)
            plt.imshow(cv2.cvtColor(output_image, cv2.COLOR_BGR2RGB))
            plt.title('Detected Waste')
            plt.axis('off')

            plt.tight_layout()
            plt.show()

    elif choice == '2':
        # Upload images
        try:
            print("Please upload an image file...")
            uploaded = files.upload()

            for filename in uploaded.keys():
                # Read image
                file_data = uploaded[filename]
                npimg = np.frombuffer(file_data, np.uint8)
                img = cv2.imdecode(npimg, cv2.IMREAD_COLOR)

                print(f"\nProcessing uploaded image: {filename}")
                output_image, detections = system.sort_waste(img)

                plt.figure(figsize=(12, 6))
                plt.subplot(1, 2, 1)
                plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
                plt.title('Original Image')
                plt.axis('off')

                plt.subplot(1, 2, 2)
                plt.imshow(cv2.cvtColor(output_image, cv2.COLOR_BGR2RGB))
                plt.title('Detected Waste')
                plt.axis('off')

                plt.tight_layout()
                plt.show()

        except Exception as e:
            print(f"Error processing uploaded image: {e}")
            print("This feature requires running in Google Colab environment.")

    elif choice == '3':
        # Use webcam
        try:
            print("Attempting to access webcam...")
            cap = cv2.VideoCapture(0)

            if not cap.isOpened():
                print("Could not open webcam. Please check your camera connection.")
                return

            print("Press 'q' to quit the webcam mode")
            while True:
                ret, frame = cap.read()
                if not ret:
                    print("Failed to grab frame")
                    break

                # Process frame
                output_image, detections = system.sort_waste(frame)

                # Display the resulting frame
                cv2.imshow('Waste Sorting System - Press q to quit', output_image)

                # Break the loop on 'q' key press
                if cv2.waitKey(1) & 0xFF == ord('q'):
                    break

            cap.release()
            cv2.destroyAllWindows()

        except Exception as e:
            print(f"Error accessing webcam: {e}")
            print("This feature may not work in Google Colab without additional setup.")

    elif choice == '4':
        # Create and use test images
        print("Creating test images...")
        mixed_waste = create_test_images()

        print("\nProcessing mixed waste image...")
        output_image, detections = system.sort_waste(mixed_waste)

        plt.figure(figsize=(12, 6))
        plt.subplot(1, 2, 1)
        plt.imshow(cv2.cvtColor(mixed_waste, cv2.COLOR_BGR2RGB))
        plt.title('Original Image')
        plt.axis('off')

        plt.subplot(1, 2, 2)
        plt.imshow(cv2.cvtColor(output_image, cv2.COLOR_BGR2RGB))
        plt.title('Detected Waste')
        plt.axis('off')

        plt.tight_layout()
        plt.show()

        # Process individual test images
        test_dir = "test_images"
        if os.path.exists(test_dir):
            for filename in os.listdir(test_dir):
                if filename.endswith(('.jpg', '.jpeg', '.png')):
                    img_path = os.path.join(test_dir, filename)
                    img = cv2.imread(img_path)

                    if img is not None and filename != "mixed_waste.jpg":
                        print(f"\nProcessing test image: {filename}")
                        output_image, detections = system.sort_waste(img)

                        plt.figure(figsize=(12, 6))
                        plt.subplot(1, 2, 1)
                        plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
                        plt.title(f'Original: {filename}')
                        plt.axis('off')

                        plt.subplot(1, 2, 2)
                        plt.imshow(cv2.cvtColor(output_image, cv2.COLOR_BGR2RGB))
                        plt.title('Detected Waste')
                        plt.axis('off')

                        plt.tight_layout()
                        plt.show()

    else:
        print("Invalid choice. Exiting demo.")
        return

    # Show statistics
    system.show_statistics()
    print(f"\nDetailed log saved to: {system.log_file}")


def setup_google_colab():
    """Setup the environment for Google Colab"""
    try:
        import google.colab
        print("Running in Google Colab environment")

        # Install required packages
        print("Installing required packages...")
        !pip install opencv-python-headless matplotlib scikit-learn pandas

        return True
    except ImportError:
        print("Not running in Google Colab environment")
        return False


if __name__ == "__main__":
    # Check if running in Google Colab
    in_colab = setup_google_colab()

    # Run the demo
    run_demo()

